#!/bin/bash

template="$1"
shift
posts_meta="$@"

usage() {
    echo \
"Usage:
    make-index <template> <post-directory>
"
    exit 1
}

[[ -n "$template" ]] || usage

make_md() {
    cat <<EOF
Alexander Lobov's blog. You can find me on
[Linkedin](https://www.linkedin.com/in/alexanderlobov) or
[Github](https://github.com/alexanderlobov).

EOF

    cat $posts_meta | \
    sort -rk1 |
    while IFS=$'\t' read date title href; do
        printf "[%s %s](%s)\n\n" "$date" "$title" "$href"
    done

    echo
}

make_md | title="Alexander Lobov's blog" ./md-to-html
