#!/bin/bash

template="$1"
shift
posts_meta="$@"

usage() {
    echo \
"Usage:
    make-index <template> <post-directory>
"
    exit 1
}

[[ -n "$template" ]] || usage

cat "$template"

for f in $posts_meta; do
    IFS=$'\t' read date title href <$f
    printf "[%s %s](%s)\n\n" "$date" "$title" "$href"
done

echo
