#!/bin/bash

template="$1"
shift
posts_meta="$@"

usage() {
    echo \
"Usage:
    make-index <template> <post-directory>
"
    exit 1
}

[[ -n "$template" ]] || usage

cat "$template"

cat $posts_meta | \
sort -rk1 |
while IFS=$'\t' read date title href; do
    printf "[%s %s](%s)\n\n" "$date" "$title" "$href"
done

echo
