#!/bin/bash

cat <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Alexander Lobov's blog - $title</title>
    <link rel="stylesheet" type="text/css" href="default.css" />
    <!--
    <style>
    body {
        width: 600px;
    }
    </style>
    -->
</head>
<body>
<div id="header">
    <div id="logo">
        <a href="/">Alexander Lobov's blog</a>
    </div>
</div>

<div id="content">
EOF

$env_markdown

cat <<EOF
</div>
</body>
</html>
EOF
