#!/bin/bash

meta_file="$1"
href="$2"

error() {
    echo >&2 $1
    exit 1
}

usage() {
    error \
"Usage:
    $0 <meta_file> <href>
"
}

[[ -n "$meta_file" ]] || usage
[[ -n "$href" ]] || usage

meta_delim="---"

read line
[[ "$line" = "$meta_delim" ]] || error "the first line should be ---"

while IFS=$': \t\n' read key value; do
    case "$key" in
        "title")
            title="$value"
            ;;
        "date")
            date="$value"
            ;;
        "$meta_delim")
            printf >"$meta_file" "%s\t%s\t%s\n" "$date" "$title" "$href"
            break;
    esac
done

full_md() {
    echo "# $title"
    echo "Posted on $date"
    cat
}

full_md | title="$title" ./md-to-html
