#!/bin/bash

meta_file="$1"
href="$2"

error() {
    echo >&2 $1
    exit 1
}

usage() {
    error \
"Usage:
    $0 <meta_file> <href>
"
}

[[ -n "$meta_file" ]] || usage
[[ -n "$href" ]] || usage

meta_delim="---"

read line
[[ "$line" = "$meta_delim" ]] || error "the first line should be ---"

while IFS=$': \t\n' read key value; do
    case "$key" in
        "title")
            title="$value"
            ;;
        "date")
            date="$value"
            ;;
        "$meta_delim")
            printf >"$meta_file" "%s\t%s\t%s\n" "$date" "$title" "$href"
            break;
    esac
done

full_md() {
    echo "# $title"
    echo "Posted on $date"
    cat
}

cat <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Alexander Lobov's blog - $title</title>
    <link rel="stylesheet" type="text/css" href="default.css" />
    <!--
    <style>
    body {
        width: 600px;
    }
    </style>
    -->
</head>
<body>
<div id="header">
    <div id="logo">
        <a href="/">Alexander Lobov's blog</a>
    </div>
</div>

<div id="content">
EOF

full_md | $env_markdown

cat <<EOF
</div>
</body>
</html>
EOF
